In [2]:
!pip install numpy

In [4]:
import numpy as np

In [6]:
day = 'Sunday'
if day == 'sunday':
    print(day)
else:
    print('night')

night


In [13]:
def dvide_numbers(x,y):
    try:
        result = x/y
        print(f'result is {result}')
    except ZeroDivisionError:
        print('Error: division by zero')
    except TypeError:
        print('Invalid input type')


dvide_numbers(10,0)
dvide_numbers(10,'a')
dvide_numbers(10,2)

Error: division by zero
Invalid input type
result is 5.0


In [1]:
list1 = [1,2,3]
type(list1)

list

In [2]:
set(list1)

{1, 2, 3}

In [3]:
import numpy as np

In [8]:
# An example of integer overflow at downcasting
arr = np.array([126,127,256], dtype='int16')
print('np array before type conversion: ' + str(arr))

arr

np array before type conversion: [126 127 256]


array([126, 127, 256], dtype=int16)

In [9]:
# Range of int8 [-128, 127], 256 overflows after conversion
arr = arr.astype('int64')
print('np array after type conversion: ' + str(arr))

np array after type conversion: [126 127 256]


In [17]:
# An example of truncated string
s = np.array(['mango', 'apple'], dtype='S3')
print(s)

[b'man' b'app']


Array

In [20]:
np.array([1,2,3],dtype='float32')

array([1., 2., 3.], dtype=float32)

In [43]:
a=np.array((1,2,3,4)).resize(3,5)
a

In [28]:
arr = np.array([[1,2,3], [4,5,6],[7,8,9]], dtype='i2')
print(arr)
print('Data Type: ' + str(arr.dtype))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Data Type: int16


In [30]:
np.arange(0,25,1).endpoint

TypeError: arange() got an unexpected keyword argument 'endpoint'

In [40]:
np.linspace(1,2,100,endpoint= False).resize(3)

ValueError: cannot resize this array: it does not own its data

In [50]:
arr = np.linspace(0, 5, 8, endpoint=False)
print(arr)

[0.    0.625 1.25  1.875 2.5   3.125 3.75  4.375]


In [51]:
np.random.rand(6,4)

array([[0.05444274, 0.02077828, 0.07961608, 0.15318046],
       [0.4833549 , 0.97054922, 0.19955557, 0.39324324],
       [0.84151846, 0.95390599, 0.09909442, 0.64274388],
       [0.76656816, 0.25003644, 0.64805595, 0.96553535],
       [0.42267672, 0.90146643, 0.75398264, 0.4976876 ],
       [0.99693251, 0.66745107, 0.75034953, 0.96028126]])

In [57]:
np.random.ranf(5)

array([0.68952078, 0.02968757, 0.12906119, 0.50822642, 0.99982278])

In [58]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [59]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [1]:
list =[1,2,3,45,8]

In [2]:
list[2]

3

In [3]:
list = [5,5,6,8,7,[2,8,9,4,5]]

In [26]:
list[5][1:3] = 0

TypeError: can only assign an iterable

In [18]:
import numpy as np
arr = np.array(range(100)).reshape(10,10)

In [34]:
arr

array([[ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [24]:
arr[0][3:6] = 0

In [27]:
# 43,44,45
# 43,44,45

In [28]:
# I want to see above value as '2.5'

In [35]:
#Create an array 100 elements and replace 0 to 99 diagonal 0
for i in arr:
    arr[i] = 2.5

IndexError: index 10 is out of bounds for axis 0 with size 10

In [42]:
arr = np.array(range(100),dtype ='f4').reshape(10,10)
arr

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14., 15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24., 25., 26., 27., 28., 29.],
       [30., 31., 32., 33., 34., 35., 36., 37., 38., 39.],
       [40., 41., 42., 43., 44., 45., 46., 47., 48., 49.],
       [50., 51., 52., 53., 54., 55., 56., 57., 58., 59.],
       [60., 61., 62., 63., 64., 65., 66., 67., 68., 69.],
       [70., 71., 72., 73., 74., 75., 76., 77., 78., 79.],
       [80., 81., 82., 83., 84., 85., 86., 87., 88., 89.],
       [90., 91., 92., 93., 94., 95., 96., 97., 98., 99.]], dtype=float32)

In [45]:

arr[0][0]= 1
arr[1][1]= 1
arr[2][2]= 1
arr[3][3]= 1
arr[4][4]= 1
arr[5][5]= 1
arr[6][6]= 1
arr[7][7]= 1

arr[8][8]= 1
arr[9][9]= 1



In [46]:
arr

array([[ 1.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [10.,  1., 12., 13., 14., 15., 16., 17., 18., 19.],
       [20., 21.,  1., 23., 24., 25., 26., 27., 28., 29.],
       [30., 31., 32.,  1., 34., 35., 36., 37., 38., 39.],
       [40., 41., 42., 43.,  1., 45., 46., 47., 48., 49.],
       [50., 51., 52., 53., 54.,  1., 56., 57., 58., 59.],
       [60., 61., 62., 63., 64., 65.,  1., 67., 68., 69.],
       [70., 71., 72., 73., 74., 75., 76.,  1., 78., 79.],
       [80., 81., 82., 83., 84., 85., 86., 87.,  1., 89.],
       [90., 91., 92., 93., 94., 95., 96., 97., 98.,  1.]], dtype=float32)

In [47]:
arr[1:3,4:6]

array([[14., 15.],
       [24., 25.]], dtype=float32)

In [50]:
# ellipsis slicing: auto-complete the dimensions
arr = np.array(range(16)).reshape(2,2,2,2)
# equivalent to arr[0,:,:,:]
# print(arr[0, ...])    

In [51]:
arr

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [55]:
arr[0][1]

array([[4, 5],
       [6, 7]])

In [52]:
arr[1]

array([[[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]]])

In [59]:
arr1 = np.arange(25).reshape((5,5))
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [57]:
a = np.array([1,2,3],dtype = np.int32)
b = np.array([1.0,2.0,3.0],dtype = np.float32)
a,b

(array([1, 2, 3]), array([1., 2., 3.], dtype=float32))

In [58]:
a+b

array([2., 4., 6.])

In [60]:
arr

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [61]:
np.where(arr>2,-1,10)

array([[[[10, 10],
         [10, -1]],

        [[-1, -1],
         [-1, -1]]],


       [[[-1, -1],
         [-1, -1]],

        [[-1, -1],
         [-1, -1]]]])

In [72]:
arr = np.array(range(100),dtype ='f4').reshape(10,10)
arr

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14., 15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24., 25., 26., 27., 28., 29.],
       [30., 31., 32., 33., 34., 35., 36., 37., 38., 39.],
       [40., 41., 42., 43., 44., 45., 46., 47., 48., 49.],
       [50., 51., 52., 53., 54., 55., 56., 57., 58., 59.],
       [60., 61., 62., 63., 64., 65., 66., 67., 68., 69.],
       [70., 71., 72., 73., 74., 75., 76., 77., 78., 79.],
       [80., 81., 82., 83., 84., 85., 86., 87., 88., 89.],
       [90., 91., 92., 93., 94., 95., 96., 97., 98., 99.]], dtype=float32)

In [76]:
list1 = [44,45,54,55]
np.where(np.isin(arr,list1),-1,arr)

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14., 15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24., 25., 26., 27., 28., 29.],
       [30., 31., 32., 33., 34., 35., 36., 37., 38., 39.],
       [40., 41., 42., 43., -1., -1., 46., 47., 48., 49.],
       [50., 51., 52., 53., -1., -1., 56., 57., 58., 59.],
       [60., 61., 62., 63., 64., 65., 66., 67., 68., 69.],
       [70., 71., 72., 73., 74., 75., 76., 77., 78., 79.],
       [80., 81., 82., 83., 84., 85., 86., 87., 88., 89.],
       [90., 91., 92., 93., 94., 95., 96., 97., 98., 99.]], dtype=float32)

In [2]:
import numpy as np
arr = np.random.rand(5,5)

In [3]:
arr

array([[0.98907135, 0.01008436, 0.15949362, 0.94070027, 0.9194258 ],
       [0.30615818, 0.74168993, 0.1732636 , 0.84333697, 0.53767612],
       [0.95377809, 0.89808332, 0.24524   , 0.58012857, 0.57863195],
       [0.83959651, 0.52745843, 0.05756212, 0.29348235, 0.65676724],
       [0.76926768, 0.74118769, 0.53853491, 0.97689931, 0.31374012]])

In [11]:
a=np.sort(arr,axis=1)
a

array([[0.27285846, 0.49728112, 0.7463968 , 0.80924945, 0.98873795],
       [0.18603774, 0.39981405, 0.52756407, 0.71028946, 0.73835682],
       [0.07497028, 0.1088564 , 0.24317712, 0.34067968, 0.85236084],
       [0.00742708, 0.16407134, 0.37419789, 0.57929175, 0.74200397],
       [0.04644703, 0.10359274, 0.4297364 , 0.46004939, 0.76247778]])

In [6]:
arr = np.random.rand(5,5)

In [7]:
arr

array([[0.49728112, 0.98873795, 0.27285846, 0.80924945, 0.7463968 ],
       [0.18603774, 0.71028946, 0.52756407, 0.39981405, 0.73835682],
       [0.07497028, 0.1088564 , 0.85236084, 0.24317712, 0.34067968],
       [0.00742708, 0.74200397, 0.16407134, 0.37419789, 0.57929175],
       [0.04644703, 0.46004939, 0.10359274, 0.76247778, 0.4297364 ]])

In [8]:
np.argsort(arr,axis=0,kind= None , order=None)

array([[3, 2, 4, 2, 2],
       [4, 4, 3, 3, 4],
       [2, 1, 0, 1, 3],
       [1, 3, 1, 4, 1],
       [0, 0, 2, 0, 0]], dtype=int64)

In [12]:
# along the row
print(np.argsort(a, axis=0))

[[3 4 2 2 1]
 [4 2 3 4 3]
 [2 3 4 3 4]
 [1 1 1 1 2]
 [0 0 0 0 0]]


In [13]:
arr = np.random.rand(3,4)

In [14]:
arr

array([[0.92944387, 0.27112401, 0.76767179, 0.03482561],
       [0.11164937, 0.43000025, 0.43855838, 0.74348966],
       [0.00720414, 0.48576744, 0.34949115, 0.52791761]])

In [15]:
arr.T

array([[0.92944387, 0.11164937, 0.00720414],
       [0.27112401, 0.43000025, 0.48576744],
       [0.76767179, 0.43855838, 0.34949115],
       [0.03482561, 0.74348966, 0.52791761]])

In [21]:
np.ndim(np.ndarray((4,5,6,6,6)))

5

In [22]:
np.ndim()

0

In [26]:
a=np.array((4,5))
b=np.array(a,ndmin=10)

In [27]:
np.ndim(b)

10

In [28]:
b.T

array([[[[[[[[[[4]]]]]]]]],








       [[[[[[[[[5]]]]]]]]]])

In [29]:
arr1 = np.arange(16).reshape((2,2,4))
arr1

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [30]:
arr1.T

array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

In [31]:
print(arr1.swapaxes(1,2))

[[[ 0  4]
  [ 1  5]
  [ 2  6]
  [ 3  7]]

 [[ 8 12]
  [ 9 13]
  [10 14]
  [11 15]]]


In [32]:
arra2 = np.arange(15)

In [41]:
arra2.shape

(15,)

In [45]:
arra2.reshape((5,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [53]:
a =arra2.resize((5,3))

In [56]:
a

In [57]:
arr1 = np.array([[1,2,3,4], [1,2,3,4]])
arr2 = np.array([[5,6,7,8], [5,6,7,8]])

In [58]:
# concat along the row
cat = np.concatenate((arr1, arr2), axis=1)        
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


In [59]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([3,4,5,6,7])

In [64]:
list =[]
for i in arr1:
    if i in arr2:
        list.append(i)
    else:
        continue

In [65]:
list

[3, 4, 5]